import total from "../images/club-category/total.png";
import computer from "../images/club-category/computer.png";

export const temp_total_posts = [
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
  {
    name: "Import",
    category: "공지",
    date: "2023.03.11",
    postTitle: "어제 우리 동아리 첫 회식!!!",
    postDetail: "어제 회식을 했다 너무너무 맛있다최고최고 짱짱짱 맛있었다",
    writerName: "정땡땡",
    likesNum: 20,
    commentNum: 20,
  },
];

export const temp_clubs = [
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
  {
    name: "Import",
    intro: "카페에서 다같이 코딩해요",
    category: "코딩",
    personnel: 35,
  },
];

export const temp_clubs_catgory = [
  { name: "전체", img: total },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
  { name: "코딩", img: computer },
];
